### ISSUE TITLE
Document comparison with Spring Cloud Contract

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/docs.pact.io#10]
![Screen Shot 2020-07-02 at 11 19 35 am](https://user-images.githubusercontent.com/53900/86305808-eea11e80-bc55-11ea-9353-e7c4b782f4df.png)

See https://pact-foundation.slack.com/archives/C5F4KFKR8/p1593623370138000

**Comment by bethesque** [comment]
The wonderful @tinexw has done this.
