### ISSUE TITLE
Broken link in junit guide

### ISSUE THREAD

**Issue by davidvc** [pact-foundation/docs.pact.io#138]
In https://docs.pact.io/implementation_guides/jvm/consumer/junit it says there is an update DSL for Java 8, but when I click on the link I get a 404 from github

The link points to https://github.com/pact-foundation/pact-jvm/blob/master/consumer/java8/README.md

**Comment by bethesque** [comment]
@uglyog where should that link point to? I checked in https://github.com/pact-foundation/pact-jvm/tree/master/consumer and can't see an obvious answer.

**Comment by uglyog** [comment]
It should be removed. There is no separate Java 8 support library, because the minimum is now Java 11.

**Comment by YOU54F** [comment]
Update to readme to point at consumer https://github.com/pact-foundation/pact-jvm/pull/1533

Should we remove this page from the site? I don't think it exists anymore as it 404s when you try to edit

 ![Screenshot 2022-04-11 at 14 51 45](https://user-images.githubusercontent.com/19932401/162754343-9a1f9077-bb9b-4271-820d-e6ce2f051f9e.png)
 
 Thanks for the spot @davidvc

**Comment by YOU54F** [comment]
This PR will remove the above page in the screenshot from the sidebar, and removes the file which is no longer updated as it doesn't exist

https://github.com/pact-foundation/docs.pact.io/pull/139
