### ISSUE TITLE
Links are barely discernible with gray accent

### ISSUE THREAD

**Issue by yuriybelike** [pact-foundation/docs.pact.io#146]
Not sure if it's a bug, but I can barely identify the links in the docs text.

https://docs.pact.io/implementation_guides/javascript

![image](https://user-images.githubusercontent.com/60257988/166318853-f630c8e7-37cc-476b-b42e-59849fcf157a.png)

**Comment by bethesque** [comment]
Yeah, it's not very accessible. I'm sure we can tweak the css.

**Comment by YOU54F** [comment]
Thanks @yuriybelike,

It appears to be this line in CSS. https://github.com/pact-foundation/docs.pact.io/blob/master/website/src/css/custom.css#L2

Links to docusaurus docs on styling - https://docusaurus.io/docs/styling-layout

I've added PR which is visible here, I've ran a lighthouse check against is and its passing in dark and light mode. There are some other accessibility issues which could do with addressing at some point.

Oddly, in the top menu, the `Getting Started` is always highlighted, even if you move to another heading, such as `Resources`.

That was the same with the existing styling, but it was hard to notice!

Preview available here https://deploy-preview-147--docs-pact-io.netlify.app/

**Comment by mefellows** [comment]
> Oddly, in the top menu, the Getting Started is always highlighted, even if you move to another heading, such as Resources.

I did notice that. I think it's to do with the paths. The menu highlighter in  docusaurus seems to highlight any menu item that's path is contained in the current URL. As `Getting Started` is `/` it's always on. 🤷
