### ISSUE TITLE
The blog index only keeps the last x entries

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/docs.pact.io#159]
I was trying to find a previous blog entry to share with a user, and realised that it's really hard to find previous blog entries, because the index on the side only shows the last 5. Hopefully there is some docusaurus config to increase this.

<img width="722" alt="Screen Shot 2022-08-05 at 10 34 56 am" src="https://user-images.githubusercontent.com/446228/182977665-a47ce406-9eb8-48a4-b4f1-b9414f35cee0.png">

**Comment by YOU54F** [comment]
Fixed

Docs -> https://docusaurus.io/docs/blog#blog-sidebar


Commit  -> https://github.com/pact-foundation/docs.pact.io/commit/864b44684778cbb49977a73dad91c192bf4520dd

**Comment by bethesque** [comment]
Thanks duck 🦆

**Comment by YOU54F** [comment]
quack quack
