### ISSUE TITLE
Links to examples in JUnit 5 docs broken

### ISSUE THREAD

**Issue by chrishowejones-sage** [pact-foundation/docs.pact.io#16]
The links to the example code for ArticlesTest and MultiTest are broken in the JVM JUnit 5 docs page https://docs.pact.io/implementation_guides/jvm/consumer/junit5/

**Comment by bethesque** [comment]
Note to self: need to fix the URL handling in the sync task.

**Comment by mefellows** [comment]
Those links are working now, so closing this off.
