### ISSUE TITLE
Current Docs Website theme does NOT support Syntax Highlighting for Java and Rust

### ISSUE THREAD

**Issue by eshack94** [pact-foundation/docs.pact.io#185]
The current theme used on the documentation website does not support proper syntax highlighting for several languages, including:
* Java
* Rust

Syntax highlighting does not render properly, even though the languages are declared properly in their respective markdown files.

For an example, see the following pages:
* https://docs.pact.io/implementation_guides/jvm/consumer/junit
* https://docs.pact.io/implementation_guides/rust/pact_consumer

**Comment by mefellows** [comment]
Thanks, care to take a look to see why that might be the case?

**Comment by YOU54F** [comment]
Just needs enabling in config, see equiv commit on our docs.pactflow.io site

https://github.com/pactflow/docs.pactflow.io/blob/dd0fbcf0412c3ba91ab7909cea5f45e5a6c1aa64/website/docusaurus.config.js#L93-L106

Would you be up for adding a contribution

**Comment by eshack94** [comment]
Thank you @mefellows and @YOU54F ! I appreciate the reply, and I absolutely would be willing to take a stab at this. I'll open a PR within the next couple days. I appreciate the response and the interest in making this improvement.

**Comment by mefellows** [comment]
Awesome, thank you!

**Comment by eshack94** [comment]
Opened PR: https://github.com/pact-foundation/docs.pact.io/pull/196

Please let me know if there are any mistakes

cc @mefellows @YOU54F

**Comment by YOU54F** [comment]
Cheers bud, one tweak and we are good to go!
