### ISSUE TITLE
Add a "was this page helpful" widget.

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/docs.pact.io#19]

**Comment by yuriybelike** [comment]
Looks like this is already implemented?

![image](https://user-images.githubusercontent.com/60257988/166318310-1eaaf79f-4f54-4ae5-9934-a47fb553acdf.png)

**Comment by bethesque** [comment]
Yep! Closing.

**Comment by YOU54F** [comment]
Thanks @yuriybelike this was completed in https://github.com/pact-foundation/docs.pact.io/pull/143 a few days ago
