### ISSUE TITLE
Diagrams not shown/included, only placeholder

### ISSUE THREAD

**Issue by hpvd** [pact-foundation/docs.pact.io#265]
Diagrams not shown/included,
only the word diagram as placeholder on:

https://docs.pact.io/implementation_guides/javascript/docs/messages

see:
![2023-05-16_11h58_39](https://github.com/pact-foundation/docs.pact.io/assets/5681880/0ab11c7d-e36b-4633-a11a-30e494cdd585)

**Comment by YOU54F** [comment]
Ahh that page is pulled in from the pact-js repo and it uses a relative link

https://github.com/pact-foundation/pact-js/blob/master/docs/messages.md?plain=1#L19

We sync it here

https://github.com/pact-foundation/docs.pact.io/blob/master/scripts/sync/pact_js.rb

We probably want to change the images so they point to an absolute link and use the images in the pact-js codebase, or copy the images are part of the `pact_js.rb` sync job and rename the entry in the markdown which is alot more convoluted.

Would you be up for updating the pact-js readme to have an absolute link?

Thanks for letting us know

**Comment by YOU54F** [comment]
Fixed in https://github.com/pact-foundation/pact-js/commit/7c239c25b62d141556a628477772dc8629b68f8e

**Comment by YOU54F** [comment]
hmm that didn't work 😅 

Should be fixed for , at least until the next doc sync see https://github.com/pact-foundation/docs.pact.io

The images are only rendered if we use `?raw=true` when the request is sent from Docusaurus.

We could cater for it in https://github.com/pact-foundation/docs.pact.io/blob/c516267f81847c032315211467eb3154ec0c9522/scripts/sync/support.rb#L10-L39

by adding it to any image files that are synced in
