### ISSUE TITLE
Slack links are expired/don't work

### ISSUE THREAD

**Issue by ScumbagScalawag** [pact-foundation/docs.pact.io#283]
The slack links [here](https://docs.pact.io/help#join-the-pact-slack-community) and [here](https://docs.pact.io/help/how_to_ask_for_help#3-find-the-appropriate-slack-channel-for-your-question) (likely elsewhere too) are expired and don't work **when clicking "signup"**.

**Comment by YOU54F** [comment]
hey, thanks for raising.

we are tracking here with a current workaround 

https://github.com/pact-foundation/devrel/issues/26#issuecomment-1721324891

**Comment by YOU54F** [comment]
Hey @ScumbagScalawag, the link should be updated now (it may expire after a certain number of signups, but we can refresh it if alerted)

**Comment by ScumbagScalawag** [comment]
@YOU54F  I was able to join. Cheers.
