### ISSUE TITLE
The documentation for pact-jvm-consumer-junit5 contains an error.

### ISSUE THREAD

**Issue by Groos-dev** [pact-foundation/docs.pact.io#298]
When I tried to run the tests using the Maven dependency(version 4.4.1) and code provided in the documentation, I encountered an error stating that "@PactConsumerTest" cannot be found. When I remove "@PactConsumerTest" and run the program,The following error occurred:
      java.lang.UnsupportedOperationException: Method createPact does not conform required method signature 'public au.com.dius.pact.core.model.V4Pact xxx(PactBuilder builder)' I modified the example code as follows to resolve the issue:
```java
@Pact(provider="ArticlesProvider", consumer="test_consumer")
  public V4Pact createPact(PactDslWithProvider builder) {
    return builder
        .given("test state")
        .uponReceiving("ExampleJavaConsumerPactTest test interaction")
        .path("/articles.json")
        .method("GET")
        .willRespondWith()
        .status(200)
        .body("{\"responsetest\": true}")
        .toPact(V4Pact.class);
  }
```

**Comment by YOU54F** [comment]
which page/doc in particular - can you provide a link to the example

**Comment by Groos-dev** [comment]
https://docs.pact.io/implementation_guides/jvm/consumer/junit5

**Comment by Groos-dev** [comment]
> which page/doc in particular - can you provide a link to the example
I'm very sorry that I couldn't describe the problem clearly, the link is https://docs.pact.io/implementation_guides/jvm/consumer/junit5

**Comment by YOU54F** [comment]
Thanks @Groos-dev 

That document source is here https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit5/README.md

and is pulled in via a sync job, so one would to update the documentation via the link above.

I imagine this document actually needs updating to reflect a supported branch, currently the readme [suggests](https://docs.pact.io/implementation_guides/jvm/consumer/junit5#dependency)

>The library is available on maven central using:

>group-id = au.com.dius.pact.consumer
>artifact-id = junit5
>version-id = 4.4.X

which is no longer a supported branch

https://github.com/pact-foundation/pact-jvm?tab=readme-ov-file#supported-jdk-and-specification-versions

![Screenshot 2023-11-10 at 12 18 18](https://github.com/pact-foundation/docs.pact.io/assets/19932401/a329efa8-8c52-4a28-b195-f9893715a5e0)

**Comment by YOU54F** [comment]
> I'm very sorry that I couldn't describe the problem clearly, the link is https://docs.pact.io/implementation_guides/jvm/consumer/junit5

No problem 👍🏾, and thank you!

**Comment by YOU54F** [comment]
I think this issue would be worth transferring this to the pact-jvm repository, if you are happy with me doing that 👍🏾

**Comment by YOU54F** [comment]
BTW, I am just testing this out as part of a separate issue and I think you might need to explicitly set the `pactVersion` to V3

See below

```
import au.com.dius.pact.core.model.PactSpecVersion
@PactConsumerTest
@PactTestFor(providerName = "ArticlesProvider", pactVersion = PactSpecVersion.V3)
```

**Comment by Groos-dev** [comment]
If I want to use the @PactConsumerTest annotation, which jar package do I need to import?

**Comment by YOU54F** [comment]
https://mvnrepository.com/artifact/au.com.dius.pact.consumer/junit5

one of these ☝🏾
