### ISSUE TITLE
Dead Link on "When to use Pact" page

### ISSUE THREAD

**Issue by andreasmarkussen** [pact-foundation/docs.pact.io#33]
The page: 

Url: https://docs.pact.io/getting_started/what_is_pact_good_for/
File: what_is_pact_good_for.md

has this item:

"Use as a general purpose mocking or stubbing tool for browser driven tests. Why?"

And it links to 

https://docs.pact.io/getting_started/consumer/

**Comment by bethesque** [comment]
Thanks, I've fixed that.
