### ISSUE TITLE
Google result has PACT not Pact for main heading

### ISSUE THREAD

**Issue by dantwining** [pact-foundation/docs.pact.io#50]
![image](https://user-images.githubusercontent.com/950341/98365034-bf4a5600-2029-11eb-9a8f-5a9bde4ccc7b.png)

I haven't been able to work out where Google is getting this from, as I can't seem to find it on the actual website, but the way that it pulls back "PACT" is unfortunate as this isn't then consistent with the Pact documentation itself.

I appreciate that it's exceptionally minor but it is annoying as it then slips into all of the references that get made to Pact, e.g. in emails between our engineers. And, yes, I'm sure that not all of the engineers will have done this based on a google search, they probably just assume that it's an acronym, but it would be nice if we could get Google at least to agree.

Perhaps this is just some cached result from a previous iteration of the Pact website, and it will correct itself over time? I don't know if there's any way to prompt Google to re-scan? Sorry, as I said it's very minor, but was hoping that someone might know of a quick fix.

**Comment by bethesque** [comment]
Hi @dantwining, funny you should mention that. The PACT thing has been driving me nuts since it started happening 5+ years ago when the Pact logo was created with all uppercase letters. It's become an ongoing joke that people now do deliberately to get a rise out of me 😆 It's so nice to meet someone else who cares about capitalization! 

I would LOOOVE to know how to fix the PACT in the google search results. I've gone through the content in the actual site, and I don't know where it's coming from. However, we've got a new marketing person in Pactflow recently - I'll see if she has some ideas.

**Comment by bethesque** [comment]
Just reading this:

> Google's generation of page titles and descriptions (or "snippets") is completely automated and takes into account both the content of a page as well as references to it that appear on the web. The goal of the snippet and title is to best represent and describe each result and explain how it relates to the user's query.
> 
> We use a number of different sources for this information, including descriptive information in the title and meta tags for each page. We may also use publicly available information, or create rich results based on markup on the page.
> 
> While we can't manually change titles or snippets for individual sites, we're always working to make them as relevant as possible. You can help improve the quality of the title and snippet displayed for your pages by following the general guidelines below.

https://support.google.com/webmasters/answer/35624?hl=en

Looks like we may not have control over what it displays.

**Comment by dantwining** [comment]
Oh that is disappointing, I can understand how lots of people searching for "PACT" would lead google to display the "What is PACT Contract Testing?" question at the bottom of the screenshot, but had really hoped that there would be some way to influence the Page Title result.

Also, I hadn't realised that you had an upper-case logo, I had always gone straight to the docs page (https://docs.pact.io/) and not seen the Pact logo on the main page (https://pact.io/) where it's uppercase. I suspect that I'll just have to learn to let it go and be more forgiving of others!

Thanks for looking at it in so much detail for me.

**Comment by YOU54F** [comment]
@dantwining thank you so much for caring! I can report that it is sorted. People with OCD can rejoice 😅 

![Screenshot 2022-04-29 at 12 36 10](https://user-images.githubusercontent.com/19932401/165937097-817c427a-000e-4556-a895-064cdb715fc6.png)

**Comment by mefellows** [comment]
> It's become an ongoing joke that people now do deliberately to get a rise out of me 😆 

If you think minor victory will solve that problem...

**Comment by bethesque** [comment]
Hoorah!
