### ISSUE TITLE
[Contract test vs functional] Documentation incomplete

### ISSUE THREAD

**Issue by HarFis** [pact-foundation/docs.pact.io#73]
The last question is not answered, but just repeated in the answer:
https://docs.pact.io/consumer/contract_tests_not_functional_tests/#does-the-provider-do-the-right-thing-with-the-request

**Comment by bethesque** [comment]
What further clarifications would you like to see in there?

**Comment by YOU54F** [comment]
Hi @HarFis, 

Just following up on this to see if you wanted to seek further clarification and if you had any suggestions 👍🏾 

Thanks!

**Comment by YOU54F** [comment]
Going to close this @HarFis, please contact us via a https:/slack.pact.io if you would like to further this conversation
